version: "3"

services:
  django:
    build: .
    command: gunicorn askme.wsgi:application --bind 0.0.0.0:8080
    ports:
      - "80:8080"

  node_exporter:
    image: prom/node-exporter
    command:
      - "--path.rootfs=/host"
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - "/:/host:ro"